version: '3.8'
services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: warehouse_db
            POSTGRES_USER: warehouse_user
            POSTGRES_PASSWORD: warehouse_pass
        volumes:
            - postgres_backup:/var/lib/postgresql/data
        networks:
            - warehouse-net

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: warehouse
        depends_on:
            - postgres
        ports:
            - 8080:8080
        networks:
            - warehouse-net

networks:
    warehouse-net:
        driver: bridge

volumes:
    postgres_backup:
