spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/warehouse_db
        username: warehouse_user
        password: warehouse_pass
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true