DROP TABLE IF EXISTS warehouse CASCADE;
CREATE TABLE warehouse(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    capacity DECIMAL(10,2) NOT NULL,
    manager_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS product CASCADE;
CREATE TABLE product(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(512) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(100) NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS inventory CASCADE;
CREATE TABLE inventory(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES product(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    quantity INT NOT NULL,
    min_stock INT NOT NULL,
    max_stock INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (warehouse_id, product_id)
);